services:
  db:
    image: postgres:13
    container_name: chapter-track-updater-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-manga-to-read}
    ports:
      - "5432:5432"
    volumes:
      - chapter-track-updater-db:/var/lib/postgresql/data
    networks:
      - chapter-track-updater-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chapter-track-updater-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SCRAPING_SERVICE_URL: ${SCRAPING_SERVICE_URL}
      PORT: ${PORT}
      CRON_SCHEDULE: ${CRON_SCHEDULE}
      NOTIFY_CRON_SCHEDULE: ${NOTIFY_CRON_SCHEDULE}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_MODEL_NAME: ${OPENROUTER_MODEL_NAME}
      API_HEALTH_CHECK_URL: ${API_HEALTH_CHECK_URL}
      HEALTH_CHECK_CRON_SCHEDULE: ${HEALTH_CHECK_CRON_SCHEDULE}
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    networks:
      - chapter-track-updater-network
    command: bash -c "npx prisma db push && npm start"

volumes:
  chapter-track-updater-db:

networks:
  chapter-track-updater-network:
